name: hive_generator_io
description: Fork of the original hive_generator project. Updated to support latest versions of Dart and Flutter!
version: 3.2.2
homepage: https://github.com/versify-llc/hive_io
repository: https://github.com/versify-llc/hive_io/tree/main/hive_generator_io

environment:
  sdk: ^3.8.0

dependencies:
  analyzer: ^9.0.0
  build: ^4.0.3
  collection: ^1.19.1
  hive_io: ^3.2.2
  source_gen: ^4.1.1
  source_helper: ^1.3.9

dev_dependencies:
  build_runner: any
  build_test: any
  lint: ^2.8.0
  test: ^1.26.3
