name: hive_flutter_io
description: Fork of the original hive_flutter project. Updated to support latest versions of Dart and Flutter!
version: 3.2.1
homepage: https://github.com/versify-llc/hive_io
repository: https://github.com/versify-llc/hive_io/tree/main/hive_flutter_io

environment:
  sdk: "^3.8.0"

dependencies:
  flutter:
    sdk: flutter
  hive_io: ^3.2.1
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  build_runner: ^2.10.1
  lint: ^2.8.0
  mockito: ^5.5.1
  test: ^1.26.3
